apiVersion: apps/v1
kind: Deployment
metadata:
  # Object to be created
  name: client-deployment
spec:
  # Numbers of pods
  replicas: 3
  # Similiar to service-node Selector
  selector:
    matchLabels:
      component: web
      
  # Configuration of each template for every pod
  template:
    metadata:
      # Label/Selector coupling (could have multiple)
      labels: 
        component: web
    spec:
      containers:
        - name: client
          image: newenay/multi-client:v6
          ports:
            - containerPort: 3000

# Could use '---' to house multiple configs within the same file if wanted
# ie: contents of client-cluster-ip-service.yaml
# ---