apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
      
  template:
    metadata:
      labels: 
        component: worker
    spec:
      containers:
        - name: worker
          image: newenay/multi-worker

          # Add Redis connection to each container
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_HOST
              value: '6379'